/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionRoleDialog: typeof import('./src/components/user-managment/role/ActionRoleDialog.vue')['default']
    ConfirmDialog: typeof import('./src/components/common/ConfirmDialog.vue')['default']
    Layout: typeof import('./src/components/layouts/basic-layout/Layout.vue')['default']
    LoadingDialog: typeof import('./src/components/common/LoadingDialog.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MAvatar: typeof import('./src/components/avatar/MAvatar.vue')['default']
    MenuSelectChip: typeof import('./src/components/user-managment/MenuSelectChip.vue')['default']
    MessageQueue: typeof import('./src/components/common/MessageQueue.vue')['default']
    MTextField: typeof import('./src/components/input/MTextField.vue')['default']
    NavCollapse: typeof import('./src/components/layouts/basic-layout/sidebar/NavCollapse.vue')['default']
    NavItem: typeof import('./src/components/layouts/basic-layout/sidebar/NavItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
