/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./src/components/common/ConfirmDialog.vue')['default']
    Dialogs: typeof import('./src/components/common/Dialogs.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MessageQueue: typeof import('./src/components/common/MessageQueue.vue')['default']
    MTextField: typeof import('./src/components/input/MTextField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./src/components/common/Snackbar.vue')['default']
    Snackbars: typeof import('@/components/common/Snackbar.vue')['default']
    SnackbarV2: typeof import('./src/components/common/SnackbarV2.vue')['default']
  }
}
